Ast expression (#66)
* updated test sources for testing of AST

* updated test sources for testing of AST

* Update Main.java

* added test

test still fails bc of
java.lang.IllegalArgumentException: Not implemented: Can't convert value of type sootup.core.jimple.common.expr.JVirtualInvokeExpr
at AST.CodeStructure.Util.convertValue(Util.java:305)

* Finished API structure, everything is implemented

* Added test sketch

* Reworked API, removed ClassDecl and MethodDecl, deleted a bunch of useless code, is now much cleaner.

* updated tests

* updated tests

* Added goto at the end of each BasicBlock for consistency

* made most tests pass, added Null

* moved Test.java to test/sources

* documentation

* Update Main.java

* Reworked API, removed ClassDecl and MethodDecl, deleted a bunch of useless code, is now much cleaner.

* Added goto at the end of each BasicBlock for consistency

* updated tests

* updated tests

* made most tests pass, added Null

* documentation

* moved Test.java to test/sources

* rm dot/api

* prettyfied AttributeReference.toString

* Use NullLiteral instead of Null

---------

Co-authored-by: TankChomper <nicjoe@outlook.de>
Co-authored-by: totallynotadolphin <totallynotadolphin@riseup.net>
Co-authored-by: Charlotte Pabst <charlotte.pabst@stud.tu-darmstadt.de>